### ISSUE TITLE
Clarifications pour question 4 et Question 6

### ISSUE THREAD

**Issue by KristerBC** [PolytechLyon/isi3-tp2-visiteur-clasen-tp2#1]
Bonsoir,
Je veut juste savoir si j'ai bien compris ses deux questions. Avec la classe ArithmeticVisitor, elle prend automatiquement en compte les règles d’arithmétique.

Souhaitez-vous un noeud "parantèse" qui modifie les priorités des calculs également?

Cordialement,
Kristoffer.

**Comment by Slashgear** [comment]
Faite gaffe au priorité des multiplication.
Mais non pas besoin de gérer les parenthèses.

**Comment by KristerBC** [comment]
Merci, je vais tester un peu des differentes equations.

**Comment by Slashgear** [comment]
Attention les noms de package en Java c'est tout en minuscule.
