### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by KristerBC** [PolytechLyon/isi3-tp2-visiteur-clasen-tp2#2]
Bonsoir,

J'ai essayé d'utiliser Dia au lieu de la fonction intégrée d'Intellij, mais je n'arrive pas trop à voir la différence des deux. 
Est-ce-que Dia à une possibilité pour insérer des Interface ?

Bien cordialement,
Kristoffer.

**Comment by Slashgear** [comment]
Ce qui me plait moyen avec les graphe d'IntelliJ ce sont les associations. Elle respectent pas la logique UML de classe. Après je comprends ton schéma. Mais il faut que tu sois au clair avec les UML de classe pour le partiel

- Rajouter un visiteur /visitable pour le calcul, je ne suis pas pour. C'est l'inverse de l'objectif du pattern Visiteur.
On peut probablement s'en sortir avec des types optionnels en Java ?

- Du coup le pattern Visiteur il sert à quoi ?

- La priorité de la multiplication, faudrait m'expliquer comment elle marche dans votre code ?

**Comment by KristerBC** [comment]
Bonsoir,

Je vous comprends tout a fait. J'ai essayé faire une petite retouche sur le diagramme d'Intellij pour ajouter les associations manquants.

J'ai maintenant supprimer le arithmiqueVisitor et introduit les optionnels pour pouvoir utiliser le visitor normal. Le raison que je l'ai pas fait au début, est parce que je trouve que ca soit un peut dommage replacer les retour de void avec des retours typés, juste pour qu'un des 3 visiteurs peut marcher.

Je vais faire une explication sur la priorité de la multiplication tout de suite

**Comment by KristerBC** [comment]
Voilà, j'ai changé question 4 et 6 dans le rapport

Dans le cas où il y a une Multiplication
plus "tôt" dans l'arbre, nous avons besoin d'introduire des parantèses dans l'affichage de l'expression arithmétique.   
Par example l'expression "2*2-3+(-4)" devient essentiellement "(2*(2+3)+(-4)) après avoir introduit les parantèses

**Comment by Slashgear** [comment]
La gestion des Optional pourrait être mieux mais on verra ça prochainement en TP.

Aller ça me suffit.
